version: "3"

services:
    php:
        build: ./php/
        container_name: "server_php"
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "./html:/var/www/html:rw"
            - "./dump:/var/dump:rw"
        networks:
            - database
        depends_on:
            - sql
        environment:
            MYSQL_ROOT_PASSWORD: "root"           

    sql:        
        image: mariadb:10.3
        container_name: "server_sql"
        restart: unless-stopped
        ports: 
            - "3306:3306"        
        volumes:
            - "sqldata:/var/lib/mysql"
        networks:
            - database
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "devel"
            MYSQL_USER: "devel"
            MYSQL_PASSWORD: "devel"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: "server_phpmyadmin"
        restart: unless-stopped
        ports:
            - "8080:80"
        networks:
            - database
        depends_on:
            - sql
        environment:
            PMA_HOST: sql

volumes:
    sqldata:
networks:
    database:
        driver: bridge